development:
  adapter: mysql2
  encoding: utf8
  database: instagram_app_development
  pool: 5
  username: root
  password: click227

test:
  adapter: mysql2
  encoding: utf8
  database: instagram_app_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: my_database_production
  pool: 5
  timeout: 5000
